package com.univsoftdev.econova.security;

public enum Roles {

    AUD_AUDITOR,
    CON_CONSULTOR,
    CON_CONTADOR_OPERADOR,
    CON_CONTADOR_PRINCIPAL,
    CON_ESPECIALISTA_CONTABILIDAD,
    CON_ESPECIALISTA_PRINCIPAL,
    CON_OPERADOR_INDICADORES,
    CON_SIMPLIFICADO,
    COS_CONSULTOR,
    COS_CONTADOR_OPERADOR,
    COS_ESPECIALISTA_COSTO,
    COS_ESPECIALISTA_PRINCIPAL,
    DB_ACCESS_ADMIN,
    DB_BACKUP_OPERATOR,
    DB_DATA_READER,
    DB_DATA_WRITER,
    DB_DDL_ADMIN,
    DB_DENY_DATA_READER,
    DB_DENY_DATA_WRITER,
    ECONOMIC_ADMIN,
    SYSTEM_ADMIN,
    
}
