/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.univsoftdev.econova.finanzas.views.otrasoperacionesbancarias;

import javax.swing.*;
import javax.swing.GroupLayout;

/**
 *
 * @author CNA
 */
public class FormOtrasObligCobro extends javax.swing.JPanel {

    /**
     * Creates new form FormOtrasObligCobro
     */
    public FormOtrasObligCobro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	//======== this ========

	GroupLayout layout = new GroupLayout(this);
	setLayout(layout);
	layout.setHorizontalGroup(
	    layout.createParallelGroup()
		.addGap(0, 400, Short.MAX_VALUE)
	);
	layout.setVerticalGroup(
	    layout.createParallelGroup()
		.addGap(0, 300, Short.MAX_VALUE)
	);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
